baseURL = "https://shinagawa-web.github.io/gomarklint/"
languageCode = "en-us"
title = "gomarklint"
theme = "hugo-book"

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookToC = true
  BookRepo = "https://github.com/shinagawa-web/gomarklint"
  BookEditPath = "edit/main/docs/content"
  BookSearch = true
  BookDescription = "A fast, opinionated Markdown linter for engineering teams. Built in Go, designed for CI."
  BookTheme = "dark"

