name: Test and Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build binary
        run: go build -o gomarklint

      - name: Run tests
        run: make test-all

      - name: Generate coverage report
        run: make test-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: shinagawa-web/gomarklint
          files: ./coverage.txt
          fail_ci_if_error: true

      - name: Lint Markdown files
        run: ./gomarklint --output junit --config .gomarklint.ci.json > gomarklint.xml
        continue-on-error: true

      - name: Publish gomarklint results
        uses: mikepenz/action-junit-report@bccf2e31636835cf0874589931c4116687171386 # v6.4.0
        if: always()
        with:
          report_paths: gomarklint.xml
          check_name: gomarklint
          fail_on_failure: true
          include_passed: true
