name: Test Action

on:
  pull_request:
    paths:
      - 'action.yml'
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'testdata/action/**'
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  test-action:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run gomarklint Action
        uses: ./
        with:
          args: testdata/action
          comment-on-pr: 'true'
          github-token: ${{ secrets.GITHUB_TOKEN }}
